from vertexai.preview.generative_models import GenerativeModel

def summarize_insights(root_responses):
    """
    Summarizes root agent responses into a final business narrative using Gemini.

    Args:
        root_responses (list): List of strings containing raw insights from root agent.

    Returns:
        str: Formatted business narrative.
    """
    model = GenerativeModel("gemini-2.5-pro")

    # Join root responses with dashes for clarity
    raw_insights_text = "\n".join(f"- {r}" for r in root_responses)

    prompt = f"""
You are a highly skilled marketing insights analyst with expertise in synthesizing complex advertising campaign data into clear, executive-level business narratives.

Context:
You are provided with raw insights generated by LLMs or analytics systems. These insights contain key performance indicators (KPIs) for a specific **brand, campaign, creative, and platform** during a defined **time period**. The KPIs may include (but are not limited to):

- Actual Spend
- Planned Spend
- Variance (Actual Spend - Planned Spend)
- Impressions
- Completed Views
- Total Clicks
- CTR % (Clicks / Impressions * 100)
- VCR % (Completed Views / Impressions * 100)
- Campaign Reach
- Campaign Frequency
- CPM $ (Actual Spend / Impressions * 1000)
- CPCV $ (Actual Spend / Completed Views)

Objective:
Your task is to analyze the provided raw insights holistically and generate a **formal business narrative** that could be presented to senior leadership.

Structure:
Your narrative must follow **this exact structure**:

Overview
Provide a concise executive summary of the overall campaign performance, focusing on high-level impact, efficiency, and engagement.

Key Trends
Identify and explain the most important trends across the KPIs (e.g., cost efficiency, engagement quality, reach expansion, performance against benchmarks). Summarize trends rather than listing individual KPI values.

Anomalies
Identify and describe any outliers, unexpected patterns, or anomalies (e.g., unusually high CPM, spikes or drops in impressions, inconsistent CTR) only if present. If no anomalies, explicitly state so.

Recommendations
Provide **actionable, strategic recommendations** based on your synthesis of the trends and anomalies. Consider future campaign optimizations in terms of creative, media buying, targeting, or messaging.

Tone & Style Requirements:
- Use **formal business language** appropriate for senior marketing executives.
- Be **concise**, **insightful**, and **strategic**.
- **Do not repeat raw insights verbatim** — your job is to synthesize and interpret.
- Use **markdown-style section headings** exactly as shown (e.g., ### Overview).
- **Do not include any preamble, instructions, or extra text.**
- Return **ONLY the narrative** — no surrounding commentary.

Input Data:
Raw insights:
{raw_insights_text}
"""

    response = model.generate_content(
        prompt,
        generation_config={
            "temperature": 0.5,
            "top_p": 1.0,
            "max_output_tokens": 2048
        }
    )

    try:
        output_text = response.text.strip() if hasattr(response, "text") else ""
        if not output_text:
            return " No summary generated. Check LLM output or token limit."
        return output_text
    except Exception as e:
        return f" Error processing summary: {e}"
